### ISSUE TITLE
浏览器无反应，mess为internal/modules/cjs/loader.js:615  throw err;     ^ Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by NeroAsmarr** [iamcco/markdown-preview.nvim#109]
安装后用命令:MarkdownPreview浏览器无反应，mess报错为：

`internal/modules/cjs/loader.js:615                                                                                                                                                       
    throw err;
    ^
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/neroasmar/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)`

环境为neovim + macos 10.15.1 + vim_plug.

请问大家谁有同样问题么？？

**Comment by iamcco** [comment]
你这安装有问题，到插件目录执行 yarn install

**Comment by NeroAsmarr** [comment]
> 你这安装有问题，到插件目录执行 yarn install

感谢！！已经可以成功运行了！

**Comment by xarthurx** [comment]
windows 10 平臺同樣問題，`yarn install` 可修正。
但是否可以更新腳本命令，使用戶不用自己到安裝目錄去修復？

**Comment by BenSYZ** [comment]
当`PlugInstall`后跳出这个分屏时

![图片](https://user-images.githubusercontent.com/42512930/72405219-0b729400-3793-11ea-85df-7dcdbc5f4058.png)

还请跳过去看一下，不要一下子`:q`就退出了，这个包有点大，下载需要一些时间。
