### ISSUE TITLE
Why I `:MarkdownPreview` will get this error? Thank you very much!

### ISSUE THREAD

**Issue by Freed-Wu** [iamcco/markdown-preview.nvim#118]
```
C:\Users\10786\vimfiles\repos\github.com\iamcco\markdown-preview.nvim/app/server.js:15
  const server = http.createServer(async (req, res) => {
                                                                ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInContext (vm.js:88:10)
    at Object.load [as default] (C:\Users\10786\vimfiles\repos\github.com\iamcco\markdown-preview.nvim\app\lib\app\load.js:33:18)
    at Object.<anonymous> (C:\Users\10786\vimfiles\repos\github.com\iamcco\markdown-preview.nvim\app\lib\app\index.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/71566182-6304d480-2af0-11ea-9a12-46e14849179a.png)
It's weird, nothing here. what's your node version?

**Comment by Freed-Wu** [comment]
```
PS C:\Users\10786> npm -v
3.10.10
```

```
const server = http.createServer(async (req, res) => {
                                                              ^

**Comment by iamcco** [comment]
I need to know nodejs version instead of npm version. And your npm version seems also too old.

**Comment by Freed-Wu** [comment]
```
Your environment has been set up for using Node.js 6.11.1 (x64) and npm.

C:\Users\10786>
```

**Comment by iamcco** [comment]
You need to upgrade your nodejs version >= 7.6.
