### ISSUE TITLE
无法预览Markdown

### ISSUE THREAD

**Issue by SpringHan** [iamcco/markdown-preview.nvim#120]
系统：Deepin 15.11桌面版
运行:MarkdownPreview时报错：
internal/modules/cjs/loader.js:800                                       
    throw err;
    ^
Error: Cannot find module 'tslib'
Require stack:
- /usr/share/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js
- /usr/share/nvim/plugged/markdown-preview.nvim/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/nvim/plugged/markdown-preview.nvim/app/lib/a
pp/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js',
    '/usr/share/nvim/plugged/markdown-preview.nvim/app/index.js'
  ]
}

**Comment by iamcco** [comment]
安装有问题，执行 `:call mkdp#util#install()` 下载预编译 bundle，或者到插件目录执行 `yarn install` 或着 `npm install`
