### ISSUE TITLE
浏览器无法打开

### ISSUE THREAD

**Issue by SpringHan** [iamcco/markdown-preview.nvim#124]
报错信息如下：
internal/modules/cjs/loader.js:983
  throw err;
  ^
Error: Cannot find module 'msgpack-lite'
Require stack:
- /home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/preloadmodules.js
- /home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/load.js
- /home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js
- /home/spring/.config/nvim/plugged/markdown-preview.nvim/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/preloadmodules.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/preloadmodules.js',
    '/home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/load.js',
    '/home/spring/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js',
    '/home/spring/.config/nvim/plugged/markdown-preview.nvim/app/index.js'
  ]
}

**Comment by SpringHan** [comment]
使用
`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & npm install', 'for' :['markdown', 'vim-plug'] }`
进行安装

**Comment by iamcco** [comment]
后面这个 `'do': 'cd app & npm install'` 安装失败了，你到插件目录下执行下 `npm install`

**Comment by SpringHan** [comment]
我刚刚尝试了一下，成功了，十分感谢！
