### ISSUE TITLE
服务器断联重启终端出现问题

### ISSUE THREAD

**Issue by Duan-Wuya** [iamcco/markdown-preview.nvim#143]
自从有一次服务器断联重启终端后会出现如下问题：
```
[markdown-preview.vim] uncaught exception: Error: listen EADDRINUSE 0.0.0.0:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
重新安装后也无济于事。
在Ubuntu下使用neovim，并且在app下进行过`yarn install`
这款插件真的很好用，谢谢！

**Comment by iamcco** [comment]
你看下是不是8080端口被占用了

**Comment by iamcco** [comment]
断联？不会之前的vim还开着吧

**Comment by Duan-Wuya** [comment]
我刚刚看了一下，端口没被占用，而且也莫名其妙的可以用了，睡一晚上就可以了hhh，谢谢你！

**Comment by Duan-Wuya** [comment]
我就close啦
