### ISSUE TITLE
ubuntu 18.04 预览 markdown 时没有反应，预览 mermaid 代码块的文件出现报错。

### ISSUE THREAD

**Issue by KylinskyChen** [iamcco/markdown-preview.nvim#244]
现象是：预览 markdown 时没有反应，预览 mermaid 代码块的文件出现报错。

报错内容如下。

```
Error detected while processing function <SNR>92_serverStart[5]..mkdp#browserStart[2]..<SNR>161_browserStart[12]..provider#python#Call:                                                        
line   18:                                                                                                                                                                                     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/base64.py", line 54, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-44: ordinal not in range(128)
Press ENTER or type command to continue
```

尝试将主的 python 版本换成 python3，但是流程图预览失败，以上报错消失，所有 markdown 文件都能预览，但不能从根本上解决问题。

请问这是什么问题，该如何解决呢？

**Comment by KylinskyChen** [comment]
尝试使用以下方式重新安装，依然无法显示，出现新的报错：

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
```

报错内容如下：

```
Error: nvim_call_function: Error calling function.
```

**Comment by iamcco** [comment]
是不是搞错插件了，这个插件没用python

**Comment by KylinskyChen** [comment]
我在 ubuntu20.04重装了一下 neovim，现在的现象是：为了排除问题，我没有安装其他相关插件，只安装了您的插件，mathjax 和 markdown-preview，使用 .nvim 后缀的那个插件 markdown-preview 没有反应，使用 .vim 后缀的那个插件能弹出 google，但是预览窗口什么都没有，也没出现任何报错，checkhealth 所有项目都是绿色，没有异常，请问这是咋回事呢？




    


在2020年10月10日 17:53，年糕小豆汤 写道： 
是不是搞错插件了，这个插件没用python

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iamcco/markdown-preview.nvim/issues/244#issuecomment-706522569",
"url": "https://github.com/iamcco/markdown-preview.nvim/issues/244#issuecomment-706522569",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by KylinskyChen** [comment]
我在 ubuntu20.04重装了一下 neovim，现在的现象是：为了排除问题，我没有安装其他相关插件，只安装了您的插件，mathjax 和 markdown-preview，使用 .nvim 后缀的那个插件 markdown-preview 没有反应，使用 .vim 后缀的那个插件能弹出 google，但是预览窗口什么都没有，也没出现任何报错，checkhealth 所有项目都是绿色，没有异常，请问这是咋回事呢？

**Comment by KylinskyChen** [comment]
非常感谢开发者的解答，我这边的问题目前解决了。

我之前一直在使用 vimplus，使用的也是您开发的这个插件，偶尔会出现一下卡顿的情况，不过一直觉得非常好用。近期需要用 mermaid 去画一些图，但是旧版 vimplus 是不支持这个预览功能的，所以我继承 vimplus 的配置到 neovim 上面来使用，遇到了以上问题。

最后发现是由于我现在的 neovim 配置中包含了以前 markdown-preiew.vim 的一些基本配置，这可能和现在的 .nvim 后缀的配置产生了冲突，在注释掉 .vim 版本配置，使用您提供的这套默认配置之后，内容成功被加载。

而使用 .nvim 后缀的插件 MarkdownPreview 没有反应、chrome 没有弹出的原因，是由于没有进入插件的 app 界面中运行 `./install.sh` 脚本导致的。

可以使用以下两种方法解决该问题：

1. 使用 iamcco 说明文档中建议的安装方式：

```
sudo apt install yarn
```

插件下载之后附上安装方法。

```
" If you have nodejs and yarn
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
```

2. 直接到插件的目录下运行一下 `install.sh` 脚本，本质上没啥区别。

```
cd ~/.vim/plugged/markdown-preview.nvim/app/
./install.sh
```

最后附上 .vim 和 .nvim 出现冲突的配置部分，如下。

```
" markdown
" let g:markdown_preview_sync_google_chrome_path = "/usr/bin/google-chrome"
" let g:mkdp_path_to_chrome = "google-chrome"
" " 设置 chrome 浏览器的路径（或是启动 chrome（或其他现代浏览器）的命令）
" " 如果设置了该参数, g:mkdp_browserfunc 将被忽略
" let g:mkdp_browserfunc = 'MKDP_browserfunc_default'
" " vim 回调函数, 参数为要打开的 url
" let g:mkdp_auto_start = 0
" " 设置为 1 可以在打开 markdown 文件的时候自动打开浏览器预览，只在打开
" " markdown 文件的时候打开一次
" let g:mkdp_auto_open = 1
" " 设置为 1 在编辑 markdown 的时候检查预览窗口是否已经打开，否则自动打开预
" " 览窗
" let g:mkdp_auto_close = 1
" " 在切换 buffer 的时候自动关闭预览窗口，设置为 0 则在切换 buffer 的时候不
" " 自动关闭预览窗口
" let g:mkdp_refresh_slow = 0
" " 设置为 1 则只有在保存文件，或退出插入模式的时候更新预览，默认为 0，实时
" " 更新预览
" let g:mkdp_command_for_global = 0
" " 设置为 1 则所有文件都可以使用 MarkdownPreview 进行预览，默认只有 markdown
" " 文件可以使用改命令
" let g:mkdp_open_to_the_world = 0
" " 设置为 1, 在使用的网络中的其他计算机也能访问预览页面
" " 默认只监听本地（127.0.0.1），其他计算机不能访问

" set to 1, nvim will open the preview window after entering the markdown buffer
" default: 0
let g:mkdp_auto_start = 0
" set to 1, the nvim will auto close current preview window when change
" from markdown buffer to another buffer
" default: 1
let g:mkdp_auto_close = 1
" set to 1, the vim will refresh markdown when save the buffer or
" leave from insert mode, default 0 is auto refresh markdown as you edit or
" move the cursor
" default: 0
let g:mkdp_refresh_slow = 0
" set to 1, the MarkdownPreview command can be use for all files,
" by default it can be use in markdown file
" default: 0
let g:mkdp_command_for_global = 0
" set to 1, preview server available to others in your network
" by default, the server listens on localhost (127.0.0.1)
" default: 0
let g:mkdp_open_to_the_world = 0
" use custom IP to open preview page
" useful when you work in remote vim and preview on local browser
" more detail see: https://github.com/iamcco/markdown-preview.nvim/pull/9
" default empty
let g:mkdp_open_ip = ''
" specify browser to open preview page
" default: ''
let g:mkdp_browser = ''
" set to 1, echo preview page url in command line when open preview page
" default is 0
let g:mkdp_echo_preview_url = 0
" a custom vim function name to open preview page
" this function will receive url as param
" default is empty
let g:mkdp_browserfunc = ''
" options for markdown render
" mkit: markdown-it options for render
" katex: katex options for math
" uml: markdown-it-plantuml options
" maid: mermaid options
" disable_sync_scroll: if disable sync scroll, default 0
" sync_scroll_type: 'middle', 'top' or 'relative', default value is 'middle'
"   middle: mean the cursor position alway show at the middle of the preview page
"   top: mean the vim top viewport alway show at the top of the preview page
"   relative: mean the cursor position alway show at the relative positon of the preview page
" hide_yaml_meta: if hide yaml metadata, default is 1
" sequence_diagrams: js-sequence-diagrams options
" content_editable: if enable content editable for preview page, default: v:false
" disable_filename: if disable filename header for preview page, default: 0
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {},
    \ 'flowchart_diagrams': {},
    \ 'content_editable': v:false,
    \ 'disable_filename': 0
    \ }
" use a custom markdown style must be absolute path
" like '/Users/username/markdown.css' or expand('~/markdown.css')
let g:mkdp_markdown_css = ''
" use a custom highlight style must absolute path
" like '/Users/username/highlight.css' or expand('~/highlight.css')
let g:mkdp_highlight_css = ''
" use a custom port to start server or random for empty
let g:mkdp_port = ''
" preview page title
" ${name} will be replace with the file name
let g:mkdp_page_title = '「${name}」'
```
