### ISSUE TITLE
:MarkdownPreview 提示 没有匹配的自动命令

### ISSUE THREAD

**Issue by YZBPXX** [iamcco/markdown-preview.nvim#255]
请问vim可以用此插件吗 ，我安装完后输入:MarkdownPreview  它提示没有匹配的这条命令

**Comment by iamcco** [comment]
`:mess` 看下有啥错误

**Comment by YZBPXX** [comment]
我刚刚弄好了 是我没下依赖， 但是他只能渲染甘特图 渲染不出时序图

**Comment by iamcco** [comment]
具体例子

**Comment by YZBPXX** [comment]
![image](https://user-images.githubusercontent.com/57928886/97959184-c08d4000-1de9-11eb-840e-d597e39f23e1.png)

**Comment by YZBPXX** [comment]
感谢大佬🙏

**Comment by iamcco** [comment]
``` sequence-diagrams
             Andrew->China: Says
             Note right of China: China thinks\nabout it
             China-->Andrew: How are you?
             Andrew->>China: I am good thanks!
            ```

**Comment by YZBPXX** [comment]
再问大哥最后一个问题  用这款插件用plantUML怎么画思维导图 我测试的渲染不了

**Comment by iamcco** [comment]
用的 markdown-it-plantuml，没试过思维导图

**Comment by YZBPXX** [comment]
弱弱的问一句怎么装好了 怎么使用🤦‍♂️

**Comment by iamcco** [comment]
啥意思没懂，我说这个插件就用的 markdown-it-plantuml，支不支持思维导图我不知道

**Comment by YZBPXX** [comment]
不知道怎么使用这个插件 。。。

**Comment by iamcco** [comment]
看文档，基本就两个命令

**Comment by YZBPXX** [comment]
嗯嗯 好的 可以加下 大佬的微信吗  ~~主要是崇拜大佬，不会总是问问题😂~~

**Comment by iamcco** [comment]
微信就不用加了吧，基本工作在用，想交流可以到这个channel https://gitter.im/neoclide/coc-cn 里面很多大佬

**Comment by YZBPXX** [comment]
嗯嗯 感谢

**Comment by YZBPXX** [comment]
请问在哪里修改渲染的后字体大小的

**Comment by iamcco** [comment]
没提供这个设置，你可以使用自己的css样式

**Comment by zighouse** [comment]
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"my.md" 3L, 63B
[vim-node-rpc] rpc error: internal/modules/cjs/loader.js:883
[vim-node-rpc] rpc error:   throw err;
[vim-node-rpc] rpc error:   ^
[vim-node-rpc] rpc error: 
[vim-node-rpc] rpc error: Error: Cannot find module 'tslib'
[vim-node-rpc] rpc error: Require stack:
[vim-node-rpc] rpc error: - /home/zhigang/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js
[vim-node-rpc] rpc error: - /home/zhigang/.vim/plugged/markdown-preview.nvim/app/index.js
[vim-node-rpc] rpc error:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[vim-node-rpc] rpc error:     at Module.require (internal/modules/cjs/loader.js:952:19)
[vim-node-rpc] rpc error:     at require (internal/modules/cjs/helpers.js:88:18)
[vim-node-rpc] rpc error:     at Object.<anonymous> (/home/zhigang/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
[vim-node-rpc] rpc error:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[vim-node-rpc] rpc error:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[vim-node-rpc] rpc error:     at Module.load (internal/modules/cjs/loader.js:928:32)
[vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[vim-node-rpc] rpc error:     at Module.require (internal/modules/cjs/loader.js:952:19) {
[vim-node-rpc] rpc error:   code: 'MODULE_NOT_FOUND',
[vim-node-rpc] rpc error:   requireStack: [
[vim-node-rpc] rpc error:     '/home/zhigang/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js',
[vim-node-rpc] rpc error:     '/home/zhigang/.vim/plugged/markdown-preview.nvim/app/index.js'
[vim-node-rpc] rpc error:   ]
[vim-node-rpc] rpc error: }
No matching autocommands
```

**Comment by iamcco** [comment]
@zighouse 安装的时候hook失败了，要么去插件文件夹的app文件夹下面执行 `yarn install` 或者 `npm install` 或者 vim里面执行 `:call mkdp#util#install()`

**Comment by zighouse** [comment]
@iamcco Thanks a greeaat lot!!! It works.
