### ISSUE TITLE
No pre-built binary available for Darwin arm64.

### ISSUE THREAD

**Issue by lishuu** [iamcco/markdown-preview.nvim#287]
**Describe the bug**
Apple M1 Chip
- Install
```shell
cd ~/.vim/bundle/markdown-preview.nvim/app
bash ./install.sh
```
- Show
```
Fetching latest release.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1101    0  1101    0     0    868      0 --:--:--  0:00:01 --:--:--   868
 No pre-built binary available for Darwin arm64.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1456409/104692281-ae614380-5742-11eb-935a-48ef82ad3d73.png)

**Comment by iamcco** [comment]
It's expected, there is not pre build bundle for ARM platform. Using `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }` instead.

**Comment by CollieIsCute** [comment]
I am not sure if I met the same issue. I use M2 macbook air.
First, I get the error msg, here is the msg.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/43088530/184166000-6d4c70a2-12c9-4be5-a735-a93fdee5b987.png">

Then, I go to `/Users/mst/.local/share/nvim/plugged/markdown-preview.nvim/app/bin/` and execute `markdown-preview-macos`, and get the following error msg.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/43088530/184165685-49aada5a-42bd-47de-a4b5-6e95b8cd2b5d.png">

Is this the same issue to @lishuu 's ?

**Comment by livrth** [comment]
Even when I try to build it by hand, tons of error occurs lmao...
I try to use very old nodejs v16 and there still a lot of errors for Darwin arm64:
```bash
[1/4] 🔍  Resolving packages...
success Already up-to-date.
> pkg@5.6.0
node:internal/child_process:420
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at fabricate (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/pkg/lib-es5/fabricator.js:55:51)
    at fabricateTwice (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/pkg/lib-es5/fabricator.js:120:5)
    at MultiStream._queue (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/pkg/lib-es5/producer.js:266:68)
    at MultiStream._next (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/multistream/index.js:86:12)
    at Meter.onEnd (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/multistream/index.js:129:12)
    at Object.onceWrapper (node:events:627:28)
    at Meter.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
