### ISSUE TITLE
markdown-preview-linux wrapper broken

### ISSUE THREAD

**Issue by shalomb** [iamcco/markdown-preview.nvim#294]
**Describe the bug**
Using pathogen to install markdown-preview.nvim

  succeeds

:MarkdownPreview silently fails

**To Reproduce**
using pathogen
1. cd ~/.vim 
2. git submodule add -f https://github.com/iamcco/markdown-preview.nvim.git      bundle/markdown-preview
3. start vim
4. issue :call mkdp#util#install()
5. exit vim
6. edit a markdown file and issue a :MarkdownPreview 
7. No preview is launched

**Expected behavior**
Expect a preview window to be launched in a browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

Log:

From vim's :messages

[vim-node-rpc] rpc error: pkg/prelude/bootstrap.js:1254
[vim-node-rpc] rpc error:       return wrapper.apply(this.exports, args);
[vim-node-rpc] rpc error:                      ^
[vim-node-rpc] rpc error:
[vim-node-rpc] rpc error: Error: ENOTDIR: not a directory, chdir '/home/unop/.vim/bundle/markdown-preview/app/bin/markdown-preview-linux'
[vim-node-rpc] rpc error:     at Object.<anonymous> (/snapshot/markdown-preview.nvim/app/index.js:0:0)
[vim-node-rpc] rpc error:     at Module._compile (pkg/prelude/bootstrap.js:1254:22)
[vim-node-rpc] rpc error:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
[vim-node-rpc] rpc error:     at Module.load (internal/modules/cjs/loader.js:610:32)
[vim-node-rpc] rpc error:     at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
[vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:541:3)
[vim-node-rpc] rpc error:     at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
[vim-node-rpc] rpc error:     at startup (internal/bootstrap/node.js:274:19)
[vim-node-rpc] rpc error:     at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
No matching autocommands

However the wrapper is correctly installed

ls -lsd /home/unop/.vim/bundle/markdown-preview/app/bin/markdown-preview-linux
41824 -rwxr-xr-x 1 unop unop 42820792 Jan 16  2019 /home/unop/.vim/bundle/markdown-preview/app/bin/markdown-preview-linux

but fails to be invoked (and seems to be issuing a chdir against itself???) and the error message corresponds to what's seen in vim's :messages

% /home/unop/.vim/bundle/markdown-preview/app/bin/markdown-preview-linux
pkg/prelude/bootstrap.js:1254
return wrapper.apply(this.exports, args);
^Error: ENOTDIR: not a directory, chdir '/home/unop/.vim/bundle/markdown-preview/app/bin/markdown-preview-linux'
at Object.<anonymous> (/snapshot/markdown-preview.nvim/app/index.js:0:0)
at Module._compile (pkg/prelude/bootstrap.js:1254:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
at Module.load (internal/modules/cjs/loader.js:610:32)
at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
at Function.Module._load (internal/modules/cjs/loader.js:541:3)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
at startup (internal/bootstrap/node.js:274:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

```
```

**Comment by iamcco** [comment]
I can't reproduce, maybe need to package with latest pkg.

**Comment by slyboots** [comment]
@shalomb I know this is probably way too late but I use git submodules to manage all of my extensions and dotfiles and I was getting a similar error to but I actually managed to figure out what the cause was.

There is a line of code in the server's index.js [here](https://github.com/iamcco/markdown-preview.nvim/blob/master/app/index.js#L5) that calls `chdir` to change the location context of the current process (_i feel like the call is unnecessary but I also dont have a lot of node experience ¯\\\_(ツ)_/¯_.) The problem though is an assumption is made about the name of the folder containing the extension.

so in my case when I installed the extension the command I used was similar to this:
`git submodule add --name=markdownpreview.nvim <repo_url> path/to/nvim/pkgdir/markdownpreview.nvim`

this messed things up for the server because the pattern that its looking for in the replacement has a `-` between markdown and preview.

I used `git mv path/to/nvim/pkgdir/markdownpreview.nvim path/to/nvim/pkgdir/markdown-preview.nvim` to correct the folder name and was then able to run the app.

After doing that though, I ended up having to delete the node_module dirs in both the root project and the app folder followed by running `yarn install` to get everything working completely

**Comment by rongshubian** [comment]
I Installed the plugin with “./install.sh v0.0.10” and modify the project name"Markdown-preview.nvim" ->"vim-Markdown-preview", then I reproduce this error.

SO ,maybe, the prebuild binary had some dependency in folder name.
package with latest pkg or keep the project folder name can resolve this.
