### ISSUE TITLE
Windows 10下git自带vim一直提示tslib缺失

### ISSUE THREAD

**Issue by xuehao** [iamcco/markdown-preview.nvim#434]
报错信息：

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"README.md" [dos] 76L, 3797B
[vim-node-rpc] rpc error: node:internal/modules/cjs/loader:936
[vim-node-rpc] rpc error:   throw err;
[vim-node-rpc] rpc error:   ^
[vim-node-rpc] rpc error:
[vim-node-rpc] rpc error: Error: Cannot find module 'tslib'
[vim-node-rpc] rpc error: Require stack:
[vim-node-rpc] rpc error: - C:\Users\xueha\.vim\plugged\markdown-preview.nvim\app\lib\app\index.js
[vim-node-rpc] rpc error: - C:\Users\xueha\.vim\plugged\markdown-preview.nvim\app\index.js
[vim-node-rpc] rpc error:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[vim-node-rpc] rpc error:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[vim-node-rpc] rpc error:     at Module.require (node:internal/modules/cjs/loader:1005:19)
[vim-node-rpc] rpc error:     at require (node:internal/modules/cjs/helpers:102:18)
[vim-node-rpc] rpc error:     at Object.<anonymous> (C:\Users\xueha\.vim\plugged\markdown-preview.nvim\app\lib\app\index.js:3:17)
[vim-node-rpc] rpc error:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[vim-node-rpc] rpc error:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
[vim-node-rpc] rpc error:     at Module.load (node:internal/modules/cjs/loader:981:32)
[vim-node-rpc] rpc error:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[vim-node-rpc] rpc error:     at Module.require (node:internal/modules/cjs/loader:1005:19) {
[vim-node-rpc] rpc error:   code: 'MODULE_NOT_FOUND',
[vim-node-rpc] rpc error:   requireStack: [
[vim-node-rpc] rpc error:     'C:\\Users\\xueha\\.vim\\plugged\\markdown-preview.nvim\\app\\lib\\app\\index.js',
[vim-node-rpc] rpc error:     'C:\\Users\\xueha\\.vim\\plugged\\markdown-preview.nvim\\app\\index.js'
[vim-node-rpc] rpc error:   ]
[vim-node-rpc] rpc error: }
No matching autocommands: User NvimMkdpRpcExit
```

Vim版本：
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2021 16:13:20)
Included patches: 1-3441
Compiled by <https://www.msys2.org/>
Huge version without GUI.  Features included (+) or not (-):
+acl               +comments          +find_in_path      +lispindent        +multi_byte        +rightleft         +terminal          +wildmenu
+arabic            +conceal           +float             +listcmds          +multi_lang        +ruby/dyn          +terminfo          +windows
+autocmd           +cryptv            +folding           +localmap          -mzscheme          +scrollbind        +termresponse      +writebackup
+autochdir         +cscope            -footer            -lua               +netbeans_intg     +signs             +textobjects       -X11
-autoservername    +cursorbind        +fork()            +menu              +num64             +smartindent       +textprop          -xfontset
-balloon_eval      +cursorshape       +gettext           +mksession         +packages          -sodium            +timers            -xim
+balloon_eval_term +dialog_con        -hangul_input      +modify_fname      +path_extra        -sound             +title             -xpm
-browse            +diff              +iconv             +mouse             +perl/dyn          +spell             -toolbar           -xsmp
++builtin_terms    +digraphs          +insert_expand     -mouseshape        +persistent_undo   +startuptime       +user_commands     -xterm_clipboard
+byte_offset       -dnd               +ipv6              +mouse_dec         +popupwin          +statusline        +vartabs           -xterm_save
+channel           -ebcdic            +job               -mouse_gpm         +postscript        -sun_workshop      +vertsplit
+cindent           +emacs_tags        +jumplist          -mouse_jsbterm     +printer           +syntax            +virtualedit
-clientserver      +eval              +keymap            +mouse_netterm     +profile           +tag_binary        +visual
+clipboard         +ex_extra          +lambda            +mouse_sgr         -python            -tag_old_static    +visualextra
+cmdline_compl     +extra_search      +langmap           -mouse_sysmouse    +python3/dyn       -tag_any_white     +viminfo
+cmdline_hist      -farsi             +libcall           +mouse_urxvt       +quickfix          -tcl               +vreplace
+cmdline_info      +file_in_path      +linebreak         +mouse_xterm       +reltime           +termguicolors     +wildignore
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -I/usr/include/ncursesw -march=x86-64 -mtune=generic -O2 -pipe -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L. -pipe -fstack-protector-strong -pipe -Wl,--as-needed -o vim.exe -lm -lncursesw -liconv -lacl -lintl -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```

`tslib` 安装情况：

```
$ yarn list
yarn list v1.22.4
└─ tslib@2.3.1
Done in 0.10s.

$ npm list
learning-vim@ C:\Users\xueha\OneDrive\learning-vim
└── tslib@2.3.1
```

**Comment by yumaohua** [comment]
咋解决的

**Comment by ShelpAm** [comment]
我也遇到这个问题了，不过我是fedora linux，报错信息如下：
```
node:internal/modules/cjs/loader:1146
  throw err;
  ^
Error: Cannot find module 'tslib'
Require stack:
- /home/shelpam/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js
- /home/shelpam/.local/share/nvim/lazy/markdown-preview.nvim/app/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/shelpam/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/shelpam/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js',
    '/home/shelpam/.local/share/nvim/lazy/markdown-preview.nvim/app/index.js'
  ]
}
Node.js v20.12.2
```
是要装tslib？

我的插件安装方式如下：
```lua
return {
  -- install without yarn or npm
  {
    "iamcco/markdown-preview.nvim",
    cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
    ft = { "markdown" },
    build = function() vim.fn["mkdp#util#install"]() end,
  }
}
```
