### ISSUE TITLE
Installation instructions insufficient

### ISSUE THREAD

**Issue by mvrozanti** [iamcco/markdown-preview.nvim#47]
I installed it through `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install' }` but when calling `:MarkdownPreview`, I don't get a new tab nor any errors. 

`$ nvim --version` : 

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
```

I also don't seem to have the command `:MarkdownPreviewStop` in console autocomplete.

**Comment by iamcco** [comment]
type `:mess` to see error message. alse type `:checkhealth` to check the info.

**Comment by mvrozanti** [comment]
Oh my bad.

`:mess`:

```
internal/modules/cjs/loader.js:651
    throw err;
    ^
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/nexor/.config/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```

**Comment by iamcco** [comment]
seems the install progress `'do': 'cd app & yarn install'` broken. remove the plugin and reinstall it maybe works. or goto the plugin directory and do `yarn install `

**Comment by mvrozanti** [comment]
`npm i -g tslib` fixed it! This looks great thank you

**Comment by iamcco** [comment]
If you do want to install the `tslib` global. You can also goto the plugin's `app` directory and do `yarn install` should just work.

**Comment by oh-** [comment]
Thanks this is what I was looking for.
