### ISSUE TITLE
  when i use :MarkdownPreview , has an error "at load (/snapshot/markdown-preview.nvim/app/lib/app/load.js:0:0)"

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [iamcco/markdown-preview.nvim#476]
**Describe the bug**
when i use :MarkdownPreview , has an error "at load (/snapshot/markdown-preview.nvim/app/lib/app/load.js:0:0)"
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  ubuntu20.04

Log:

```
```

**Comment by falko-strenzke** [comment]
I have the same problem on Debian 11 after a recent update to commit 
```
commit 02cc3874738bc0f86e4b91f09b8a0ac88aef8e96 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by cyliu-99** [comment]
I encouter the same problem after updating plugins.

**Comment by falko-strenzke** [comment]
I rolled back to commit e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143, that is still working for me.

**Comment by gergap** [comment]
Same problem here on Deb11. Reverting to previous commit like falko-strenzke said fixed the issue for me too.

**Comment by jsolbrig** [comment]
Same problem, but on Mac.

**Comment by vds2212** [comment]
Same problem, but on Windows 10.

**Comment by vds2212** [comment]
It seems that the last commit that doesn't have the problem is: d7f95e8
With the next commit 9beccee (tag v0.0.10) the problems come.

**Comment by vds2212** [comment]
By forcing downloading `markdown_preview.nvim\app\bin\markdown-preview-win.exe` it solves the problem.
You can achieve that by running on Windows:
```
markdown_preview.nvim\app\install.cmd
```
You can achieve that by running on Linux:
```
markdown_preview.nvim\app\install.sh
```
