### ISSUE TITLE
Executing command `:MarkdownPreview` does occur a error `cannot execute binary file` in Vim on Cygwin.

### ISSUE THREAD

**Issue by tadahito18081** [iamcco/markdown-preview.nvim#530]
**Describe the bug**

Executing command `:MarkdownPreview` does occur a error `cannot execute binary file` in Vim on Cygwin.

**To Reproduce**

1. Open markdown file in Vim on Cygwin.
2. Execute command `:MarkdownPreview`.
3. See error: `/cygdrive/.../home/.../markdown-preview.nvim/app/bin/markdown-preview-linux: cannot execute binary file`

**Expected behavior**

Automatically open default browser and preview the markdown file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Environment: Cygwin
 - nvim or vim: Vim
 - Version or Vim: 8.2.4372

Log:

```
/cygdrive/.../home/.../markdown-preview.nvim/app/bin/markdown-preview-linux: cannot execute binary file
```

**Comment by tadahito18081** [comment]
Maybe, [this part](https://github.com/iamcco/markdown-preview.nvim/blob/e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143/autoload/mkdp/util.vim#L61) of the code cause the issue.

> function! mkdp#util#get_platform() abort
>   if has('win32') || has('win64')
>     return 'win'
>   elseif has('mac') || has('macvim')
>     return 'macos'
>   endif
>   return 'linux'
> endfunction

## Actual

`: echo has('win32') || has('win64')` returns 0.

## Expect

`: echo has('win32') || has('win64')` returns 1.

**Comment by tadahito18081** [comment]
I think that it will be working well, if there is a statement that check the platform is Cygwin.

Like this:
```
if has('win32') || has('win64') || has('cygwin')
return 'win'
```

But vim does not provide `has('cygwin')`.

**Comment by tadahito18081** [comment]
> But vim does not provide `has('cygwin')`.

I found builtin command for do that in vim help's [feature-list](https://vimhelp.org/builtin.txt.html#feature-list) 😄 

> win32unix               [Win32](https://vimhelp.org/os_win32.txt.html#Win32) version of Vim, using [Unix](https://vimhelp.org/os_unix.txt.html#Unix) files (Cygwin)

And the following comamnd returned value `1` ! : `:echo has('win32unix')`.

I am going to create falk and make a pull request !!

**Comment by tadahito18081** [comment]
It occured the following error, when I executed `:MarkdownPreview` after updating the code(fd95032c3f5ba3f019cc3cbc6dae87e183e8aff1).

```
pkg/prelude/bootstrap.js:1833
      throw error;
      ^
Error: ENOENT: no such file or directory, open '/cygdrive/e/cygwin64/home/tadahito/.vim/plugged/markdown-preview.nvim/app/server.js'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it fr
om filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:753:32)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1039:36)
    at load (C:\snapshot\markdown-preview.nvim\app\lib\app\load.js)
    at Object.<anonymous> (C:\snapshot\markdown-preview.nvim\app\lib\app\index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '/cygdrive/e/cygwin64/home/tadahito/.vim/plugged/markdown-preview.nvim/app/server.js',
  pkg: true
}
```

At now, I have no idea how to solve it...
